### ISSUE TITLE
Explore: Authentication

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-crd-explorations#16]
# Background

Currently, CF on VMs relies on UAA for authentication and looks at specific permissions for roles for authorization. These CF user roles are heavily coupled with the existing CC database. We want to understand what authentication would look like in CF-on-K8s, with CRDs as the source of truth and a shim exposing the CF API.

In particular, we'd like to answer the following questions:
* What's the best [authentication strategy](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authentication-strategies) for our use case?
  - the answer to this question is probably [OpenID Connect](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens)
    - which identity providers can we support?
    - do we need something like [Dex](https://dexidp.io/)?
* How would this strategy work for `kubectl` users?
* How would this strategy work for `cf` users?
  - can we implement [`cf login`](https://cli.cloudfoundry.org/en-US/v6/login.html) on top of this?
  - what about [`cf create/delete-user`](https://docs.cloudfoundry.org/adminguide/cli-user-management.html)?

# Resources

* [CF on K8s Auth N/Z](https://docs.google.com/document/d/1xt9bF7W43X_l_AfYoxoiTmWwIKKgPOz-Wk6FiRx2O24/edit)

# Deliverables

* A document with all our findings
* Can we prove the `cf` authentication flow would work agains our shim?
  - Can we build a dummy shim only exposing login endpoints which successfully delegates authentication to Kubernetes/OIDC?
  - Do we need to implement a `cf` plugin?

**Comment by danail-branekov** [comment]
## `cf login`

- cf login relies on both the API and UAA
- first it call the `/` endpoint of the API to get a list of supported
  operations foloowed by `GET /v3`
- Then it picks up the `login` operation and performs `GET /login`.
- The CLI starts the credentials prompt
- It performs `POST /oauth/token` on the `login` operation endpoint and
  receives `access_token`, `id_token` and `refresh_token` and a bunch of scopes
- After receiving the tokens it lists the organisations `GET
  /v3/organizations?order_by=name` and asks the user to choose an org
- Afterchoosing an org, the CLI would perform
  `/v3/spaces?order_by=name&organization_guids=3b7323f3-d1c2-40e7-8724-da51b33014e0`
  to get the details of the org and space and put them into the
  `~/.cf/config.json` file.

It seems that the request-response interaction above is out of scope for the
authentication/authorisation spike so we could start small. We could split the
efforts into the following directions:

1. Implement a separate cf plugin/command e.g. `cf k8s-login` that
authenticates against an identity provider over OIDC. Once the provider returns
the token, put it into the `~/.cf/config.json` file

2. Prove that once the token is available in the `~/.cf/config.json`, it does
get sent to the CF API when running `cf apps` or `cf app <app name>` and figure
out how the token is supplied into the request


3. Enhance the [`/apps` endpoint of the
cfshim](https://github.com/cloudfoundry/cf-crd-explorations/blob/main/cfshim/handlers/app_handler.go)
to get the token from the request and make it available to the K8S client. We
could prove that the token is taken into consideration via introducing role
bindings that allow/deny listing applications for particular users. As an
implementation note, we could have a middleware handler that configures the K8S
client with that token so that this step is transparent to the actual "business
logic" of getting apps (or whatever the operation is).


## `cf create-user`

OIDC is not meant to manage users, instead it only provides authentication
capabilities. Therefore it seems that we would not be able to implement that
feature over OIDC. As a matter of fact this kind of make sense as `cf` is not
supposed to manage identity providers, especially in corporate environments
with complex IDP solutions.
In the CF on VM world this feature is implemented via the CLI talking directly
to UAA, however this is not guaranteed when relying on OIDC.

**Comment by gcapizzi** [comment]
Today we wanted to verify that an OIDC token (e.g. produced by Dex via GitHub) could be used inside the shim to query the Kubernetes API.

To do so, we set up a cluster which used Dex (backed by GitHub) as it authentication provider and was set up to work with the shim. We ran the shim locally, as specified in the README.

Then we generated a token with Dex using their [example-app](https://github.com/dexidp/dex/tree/master/examples/example-app) (instructions [here](https://github.com/eirini-playground/auth-explore/tree/master/dex-auth)), and [hardcoded it](https://github.com/cloudfoundry/cf-crd-explorations/blob/3728fb9e53683e2bd93c24df0018e4ac4afa7eed/cfshim/handlers/app_handler.go#L100) in the shim. We then run the shim and tried to `GET /v3/apps`, which resulted in an error explicitly telling us that our user (`oidc:danail-branekov`) was not allowed to list apps. 

At this point we:
* applied the [`app-viewer-role` `ClusterRole` configuration](https://github.com/cloudfoundry/cf-crd-explorations/blob/main/config/rbac/app_viewer_role.yaml)
* created a `ClusterRoleBinding` from `app-viewer-role` to `oidc:danail-branekov`:
    ```
    kubectl create clusterrolebinding dani-app-viewer --clusterrole=app-viewer-role --user=oidc:danail-branekov
    ```
* tried again and... boom!
    ```
    $ http http://localhost:81/v3/apps
    HTTP/1.1 200 OK
    Content-Length: 17
    Content-Type: application/json
    Date: Wed, 07 Jul 2021 15:58:26 GMT

    {
        "resources": []
    }
    ```

Next steps:
1. Extract the token from the `Authorization` header in the request instead of hardcoding it. 
2. Perform the token extraction and client instantiation in a middleware, so that it can be reused in all handlers. To do so, we could store the newly instantiated client inside the request `Context` as a value (see [here](https://drstearns.github.io/tutorials/gomiddleware/#secmiddlewareandrequestscopedvalues) for an example)
3. Decide which client to use: at the moment we're using the `client.Client` from `controller-runtime` to minimise code changes, but given we will need a request-scoped client, we won't be able to leverage its cache. This should be fine as it's just for shim (which is essentially a Kubernetes client).

**Comment by gcapizzi** [comment]
Now that we have proved that we can authenticate against a cluster, via the shim, using an ID token produced by the identity provider, we need to think about how to integrate the `cf` CLI into the flow. We're going to spin up a separate story for that, so closing this!
