### ISSUE TITLE
Spike: authenticate the `cf` CLI with OIDC

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-crd-explorations#28]
# Background

In #16, we have proved that we can get the shim to call the Kubernetes API on behalf of the user using OIDC tokens. We now want to understand if it's possible to make `cf` authenticate using OIDC tokens too. We know that the authentication flow currently implemented by `cf` is coupled with UAA and would not work against an OIDC provider.

# What to do

* Explore [OIDC flows](https://openid.net/specs/openid-connect-core-1_0.html) and understand which flow we should implement.
* Explore ways to produce an OIDC token via the `cf` CLI. Options could be:
    1. Read the token from the user's `$KUBECONFIG`
    2. Implement a [plugin](https://docs.cloudfoundry.org/cf-cli/develop-cli-plugins.html)
    3. Add the new flow to the CLI
        - In this case, how could we make sure that the new flow would only be used on cf-on-k8s foundations?
            - CLI flag?
            - can we detect this via the `/login` call?
    
    Given all OIDC authentication flows seem to rely on redirects, explore mechanisms like the one implemented by [`fly`](https://concourse-ci.org/fly.html) to spin up a local HTTP server that can receive the redirect.

**Comment by kieron-dev** [comment]
Here is a sequence diagram showing a possible flow for OIDC Authorization Code flow with the CLI and the Shim: https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgT0lEQyBBdXRob3JpemF0aW9uIENvZGUgRmxvdwoKQWN0b3IgQWxpY2UKAAEFLT4rQ0YgQ0xJOiBjZiBsb2dpbgoKAAwGLT4rU2hpbTogR0VUIC8AFQZub3RlIHJpZ2h0IG9mIAAZBlNoaW0gaXMgdGhlIGNsaWVudCBvciBSZWx5aW5nIFBhcnR5IChSUCkKU2hpbS0-K09QAEwHZGlzY292ZXJ5LXVybApPUC0tPi0AbAZhdXRoIGVuZHBvaW50AGYPT1A6IE9QAGkIT3BlbklEIFByb3ZpZGVyAF4GLT4tAIFNCExvZ2luIFVSTACBNQZsZWYAgS8LaW5jbHVkZXMgc2NvcGU6b3BlbmlkLCByZXNwb25zZV90eXBlOmNvZGUsAIFSB19pZDogPElEPiwgcmVkaXJlY3RfdXJpOiA8VVJMPgCCMAktPi0Agl4FOiBDbGljayBVUkwgdG8AglYIAIJwCEZpcmVmb3gAgRwIdG8gT1AKAA4HAIIgB2F1dGhlbnRpYwCDQwZkYW5jZQCCIgcANQkAgQEIIHRvAIMMBQCBWw4AXAkAgWMJAIJXBWNvZGUAYQsAgmsLAIF1CAoAgyMMZ2V0IGlkX3Rva2UAg30HAIJBCE9QAIN3CgCBKQVkIHdpdGggT1AAg0QNADQJAIN-BwCEUwZwZXJzaXN0IABTBSBhZ2FpbnN0IGNvb2tpAHgIAIFeDGRvbgCBKwoAgloKABIFAIU6FGFwcHMAhTwQLwAQBQB5DGdlAHoHAIUZB2s4cwCBawYAIAoAhEULAEgMAINdCmFwcHMgbGlzdA&s=default

This keep the token very secure and away from the end user, but relies on state being persisted in the shim, and a session being established between the CLI and the Shim. Both of these points probably mean the implicit flow would be more simple and less intrusive to the CLI.

**Comment by kieron-dev** [comment]
Here's a sequence diagram from the implicit flow. This would be driven from the CLI rather than the shim, and makes use of a local http server, like `fly` uses: https://www.websequencediagrams.com/?lz=dGl0bGUgT0lEQyBJbXBsaWNpdCBGbG93CgpBY3RvciBBbGljZQoAAQUtPitDRiBDTEk6IGNmIGxvZ2luCgoADAYtPitTaGltOiBHRVQgLwAVBm5vdGUgcmlnaHQgb2YgABkGU2hpbSBpcyB0aGUgY2xpZW50IG9yIFJlbHlpbmcgUGFydHkgKFJQKQpTaGltLT4rT1AATAdkaXNjb3ZlcnktdXJsCk9QLS0-LQBsBmF1dGggZW5kcG9pbnQAZg9PUDogT1AAaQhPcGVuSUQgUHJvdmlkZXIAXgYtPi0AgU0ITG9naW4gVVJMAIE1BmxlZgCBLwtpbmNsdWRlcyBzY29wZTpvcGVuaWQsIHJlc3BvbnNlX3R5cGU6Y29kZSwAgVIHX2lkOiA8SUQ-LCByZWRpcmVjdF91cmk6IDxVUkw-AIIwCS0-LQCCXgU6IENsaWNrIFVSTCB0bwCCVggAgnAIRmlyZWZveACBHAh0byBPUAoADgcAgiAHYXV0aGVudGljYXRpb24gZGFuY2UAgiIHADUJAIEBCCB0bwCDDAUAgVsOAFwJAIFjCQCCVwVjb2RlAGELAIJrCwCBdQgKAIMjDGdldCBpZF90b2tlAIN9BwCCQQhPUACDdwoAgSkFZCB3aXRoIE9QAINEDQA0CQCDfgcAhFMGcGVyc2lzdCAAUwUgYWdhaW5zdCBjb29raQB4CACBXgxkb24AgSsKAIJaCgASBQCFOhRhcHBzAIU8EC8AEAUAeQxnZQB6BwCFGQdrOHMAgWsGACAKAIRFCwBIDACDXQphcHBzIGxpc3Q&s=default

This is better for storing id tokens locally. The implicit flow however has no ability to use refresh tokens.

**Comment by gcapizzi** [comment]
Looking at the CLI code, we found it uses OAuth (2?) to talk to UAA, but using flows that can't be used with OIDC (`password` and `client_credentials`). In particular, `cf login --sso` prompts the user for a passcode that needs to be generated separately, and then uses the `password` grant type to authenticate.

**Comment by kieron-dev** [comment]
![OIDC Implicit Flow (1)](https://user-images.githubusercontent.com/30794658/125089482-51799100-e0c6-11eb-9085-ef1f626d4cd4.png)

-- inlining the picture for the implicit flow, which seems the best candidate for a cf cli oidc login

**Comment by kieron-dev** [comment]
### Experiment: use an id token from dex, hack it into the `~/.cf/config.json`, and see if we pass it through to the shim.

We replaced "AccessToken" in the config.json with the id token from dex.

On running `cf apps`, the CLI panicked. This is because the id token does not contain the claims `user_name` or `client_id`: https://github.com/cloudfoundry/cli/blob/5cfbf04b1e06e0fb7354ac8f37992775896ef465/util/configv3/json_config.go#L345-L348.

We modified that code to expect `name`, `sub` and `iss` for `user_name`, `user_id` and `origin`, and then the code stopped panicking. Finally, modifying `Target` in `config.json` to point to our locally running shim allowed us to successfully contact the shim.

The apps list worked fine when a cluster role binding for that user existed. And on deleting that binding, we saw the error propagated back through the CLI.

**Comment by gcapizzi** [comment]
While playing with tokens extracted from `$KUBECONFIG` we realised that GKE tokens are not OIDC tokens :(
```

**Comment by gcapizzi** [comment]
Today we managed to build a [`cf` plugin](https://github.com/eirini-playground/auth-explore/tree/master/oidc-login-plugin) based on the code from the [Dex `example-app`](https://github.com/dexidp/dex/tree/master/examples/example-app) and have an almost end-to-end experience!

The plugin prints a URL to the authentication provider and spins up a local HTTP server to receive the callback. The flow implemented is actually the Authorization Code one (because that's what the `example-app` used), so once the callback is received, the plugin exchanges the authorization code for a token and it stores it in the CLI config.

We managed to run a full `cf oidc-login` > `cf apps` flow, but there's a gotcha. This only works when starting from an existing, working CLI configuration. When we tried to do this starting from a clear config (we deleted `~/.cf`), we realised that a bunch of fields are required:
* `Target` needs to be initialised with the shim URL. If we try to set it via `cf api`, then the CLI will try to hit the `/` endpoint and fail.
* `OrganizationFields` and `SpaceFields` also need to be initialized, and doing so via `cf target` fails in a similar way (the CLI will try to hit `/v3/organizations`).

**Comment by georgethebeatle** [comment]
Today I managed to finish the end-to-end cf cli flow that requires no manual editing of the cli config and proves that the cli will not  get in the way by calling `/login` unexpectedly. The complete guide on how to set everything up is [here](https://github.com/eirini-playground/auth-explore/blob/master/oidc-login-plugin/README.md)

Another interesting finding was that the implicit grant flow that we talk about above has been deprecated and we should probably use the [PKCE flow](https://pragmaticwebsecurity.com/articles/oauthoidc/from-implicit-to-pkce.html).

**Comment by georgethebeatle** [comment]
Closing this issue since we have logged #33 to look into the auth flows more closely
