### ISSUE TITLE
Explore: KubeFed

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/cf-crd-explorations#73]
As we try to design a mapping for orgs and spaces (see #69), we are trying to understand how to manage organisations that might not fit in a single cluster. Our current prototype consists of a controller connecting to multiple clusters, reconciling `Namespace`s, `Role`s and `RoleBinding`s. This requires the controller to know about all the clusters that are part of the foundation and how to connect to them.

The Kubernetes [SIG Multicluster](https://github.com/kubernetes/community/tree/master/sig-multicluster) is trying to solve a similar problem: providing a way to federate multiple clusters and reconcile resources across them. They have created a product called [KubeFed](https://github.com/kubernetes-sigs/kubefed):
> Kubernetes Cluster Federation (KubeFed for short) allows you to coordinate the configuration of multiple Kubernetes clusters from a single set of APIs in a hosting cluster. KubeFed aims to provide mechanisms for expressing which clusters should have their configuration managed and what that configuration should be. The mechanisms that KubeFed provides are intentionally low-level, and intended to be foundational for more complex multicluster use cases such as deploying multi-geo applications and disaster recovery.

Let's take a look at KubeFed and see if it might be useful for our use case. Ideally we would be able to implement orgs and spaces for individual clusters, and then use KubeFed to extend foundations on multiple clusters.

**Comment by mnitchev** [comment]
We played a bit with kubefed and found the taht it allows you to create resources accross multiple clusters with several options:
1. you can federate a resource and propagate it across all clusters (the same resource will be created on each cluster)
1. federated resources can be any kuberentes resource including crds, but they need to be enabled
1. you can generate a federated resource off of the yaml of any resource and then apply it with kubectl
1. you can **only** create federated resources in federated namespaces
1. federated resources can specify which clusters they need to be propagated to. This is done either by naming the specific cluster or with a label selector
1. resources like deployments can use the [ReplicaSchedulingPreference](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#replicaschedulingpreference) to distribute load accross multiple clusters.
1  a ReplicaSchedulingPreference for every deployment. It also looks like it overrides the deployment's replica count.

We think that this tool could be used with eirini to distribute workloads accross multiple clusters and also to ensure isolation - for example an organization can be isolated on a deticated cluster, while the rest of the organizations can be placed in a shared (or multiple) cluster. We should explore the implication of federated clusters on our authorization (RBAC and OPA) concepts.
**__NOTE:__** the kubefed product is currently in beta.

**Comment by danail-branekov** [comment]
parking for now, we know how kubefed works, now we need to know whether it would be useful for us

**Comment by georgethebeatle** [comment]
Here are the results of some experiments we ran today. We played with the idea of having sub-eirini level federation vs having super-eirini level federation:

1. Can eirini federete statefulsets? (sub-eirini federation)

   - No. As written in the docs the replicaschedulingpreference reconciler would only reconcile Deployments and ReplicaSets: https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#replicaschedulingpreference
   - It is possible to federate statefulsets without using the replicaschedulingpreference and it results in each cluster having its own 0 instance, which might be the reason why  replicaschedulingpreference does not support statefulsets.
   - This means that federation on sub-eirini level is unfeasible unless eirini swithches to deployments

2. Can we somehow use replicaschedulingpreference for LRPs/Tasks? (super-eirini federation)

   - Can we switch federation on and off by introducing a reconcliler that turns an LRP into a FederatedLRP?
     - This way neither the shim nor eirini will know about federation, but there will be a simple reconciler that just federates Tasks and LRPs. A problem with this approach might be that the app will momentarily appear on the federation host cluster before being scheduled on its destination cluster(s) which might be a security issue 

   - How are we going to work around the fact that LRP has an "instances" field while the kubefed reconcilers know how to put "replicas" on the object referred to by a replica scheduling preference?
      - Either migrate to replicas, or write our own "eirini scheduling preference" reconciler that heavily reuses the replicaschedulingpreference reconciler
   - Is replicaschedulingpreference going to work with a modified LRP that has "replicas" instead of "instances"?
     - Yes. However the LRP needs to also have a selector (as in Deployments) since the replicaschedulingpreference expects this. Once we did that, we were able to federate a LRP with a preference of 6 instances an have them distributed around 2 clusters

**Comment by danail-branekov** [comment]
> This way neither the shim nor eirini will know about federation, but there will be a simple reconciler that just federates Tasks and LRPs. A problem with this approach might be that the app will momentarily appear on the federation host cluster before being scheduled on its destination cluster(s) which might be a security issue

We can mitigate this by changing Eirini creation interface to return objects (that are not pushed to k8s). Then the federation bit could be just a wrapper (injected only when the federation switch is on) that transforms the statefulset/deployment object into a federated one and then apply it to k8s.

This is what `kubefedctl federate --filename some-deployment.yml` does, see [here](https://github.com/eirini-playground/auth-explore/blob/77cd2c80bf8b3b704e530218d026cfca1b775c26/kubefed/deploy.sh#L40) for reference. The `federate` command just transforms the yaml, pushing the object to k8s is taken care of by an upstream component.
