### ISSUE TITLE
Explore: Hierarchical Namespaces for Orgs and Spaces

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry/cf-crd-explorations#75]
While investigating the [efficiently listing a resource story](https://github.com/cloudfoundry/cf-crd-explorations/issues/71) we noticed a tool that might help with our Orgs and Spaces design. The tool is [Hierarchical Namespaces](https://github.com/kubernetes-sigs/hierarchical-namespaces) and as the name suggests it lets you create a hierarchical relationship between namespaces, which can be used to represent orgs and spaces. The tool itself works by propagating Roles and RoleBindings (by default; it can also be used to propagate any resource), which sounds like it can be a direct replacement to the Org and Space CRDs that we spiked out previously. It can also give users permissions to create subnamespaces without actually having the permission to create cluster-wide namespaces.

Lets re-evaluate our spike assuming we choose to use this tool.

**_NOTE:_** The project states that it is not yet GA, however it looks like the v1.0 is likely to be released by the end of the year.

**Comment by kieron-dev** [comment]
### Notes

With the [Hierarchical Namespaces](https://github.com/kubernetes-sigs/hierarchical-namespaces) controller (HNC), we can completely replace our previously suggested implementation of orgs, spaces and users. Below we briefly describe the HNC functionality, and how we can apply that to the org / space and permissions domain in CF.

#### Hierarchical Namespaces Overview

The tool allows construction of a namespace tree, and by default propagates Roles and RoleBindings created in a namespace to all descendant namespaces in the tree.

Any namespace can be included in a namespace tree by defining a parent/child relationship, but an interesting feature of HNC is that of _sub-namespaces_. It is possible to give permission to a user to create a sub-namespace from a particular namespace. This uses the namespaced `SubNamespaceAnchor` resource. HNC will use this to create a k8s namespace, labelled as a sub-namespace for HNC. Thus a user without namespace creation permissions can actually create sub-namespaces of a particular namespace or sub-namespace.

HNC comes with a kubectl plugin that can be used to visualise and manage the namespace trees. For example:
```
❯ kubectl hns tree cf
cf
├── [s] org1
│   ├── [s] space1
│   └── [s] space2
└── [s] org2
    ├── [s] space3
    └── [s] space4

[s] indicates subnamespaces
```

#### Applying HNC to CF Orgs, Spaces and User Roles

Let us suppose we bootstrap the system to have a root namespace called `cf`. This is a normal namespace, but the name is important. We will use it to bind permission for admin users.

##### `cf create-org`

Consider the command `cf create-org ORG`. This is available only to users with the global `admin` role. To implement this, we can create a sub-namespace of `cf` with the org name. The kubectl plugin command to achieve this would be `kubectl hns create -n cf ORG`.

We can restrict this to the `admin` role by creating a role binding for the admin user in the `cf` namespace to a role that allows the create verb on the `hnc.x-k8s.io/subnamespaceanchors` resource.

#### `cf create-space`

Now users with the `admin` or `org-manager` role can create spaces in an org. So we could implement the command `cf create-space -o ORG SPACE` with the equivalent of `kubectl hns create -n ORG SPACE`, creating SPACE as a sub-namespace of ORG. Note that some naming work is required to ensure the uniqueness of SPACE.

The user must have create permissions on the `hnc.x-k8s.io/subnamespaceanchors` resource in the ORG namespace. Now the admin user will already have this, because the RoleBinding giving that permission on the `cf` namespace will have been propagated by HNC to the ORG namespace automatically. For an `org-manager` user to have permission, we must ensure we have a RoleBinding in the ORG namespace to a role allowing the create verb on the `hnc.x-k8s.io/subnamespaceanchors` resource.

#### Restricting Tree Depth

With the setup described above, an admin user, or an org-manager user in the ORG organisation, would have the ability to create a sub-namespace of SPACE. This doesn't make sense in the CF model. So we would like to restrict the propagation of roles to disallow this.

For the org-manager RoleBinding, this is possible by adding the annotation `propagate.hnc.x-k8s.io/none: "true"`.

For the admin RoleBinding, instead we can use a label selector annotation such as `propagate.hnc.x-k8s.io/select: "cloudfoundry.org/org=true"`. We must then label all the org-level namespaces with the label `cloudfoundry.org/org: "true"`. Then the admin namespace creation permission will be propagated to all orgs, but no lower.

#### `cf delete-space`

Space deletion permissions can also be controlled using the `hnc.x-k8s.io/subnamespaceanchors` resource. So the equivalent of `kubectl delete hnc.x-k8s.io/subnamespaceanchors -n ORG SPACE` is sufficient to make HNC delete the namespace for the space. This will remove all apps in the space, and remove all role bindings, hence space users.

#### `cf delete-org`

It is also possible for a admin user to delete an org. By default, HNC will prohibit namespace deletion when the namespace has child spaces. But it is possible to set an attribute on the namespace to allow cascading deletion. E.g. `kubectl hns set --allowCascadingDeletion`. Then removing the `hnc.x-k8s.io/subnamespaceanchors` resource for the ORG will trigger a cascading deletion of the org and its spaces.

#### User Management

Just as there is no need for org or space custom resources when using HNC, we can also do without any user custom resources. They can be completely implemented with RoleBindings.

To create an admin user, we need to create two RoleBindings in the `cf` namespace:
* one granting all the admin permissions on the CF custom resources
* one granting the SubNamespaceAnchor management permissions, with the `propagate.hnc.x-k8s.io/select: "cloudfoundry.org/org=true"` annotation.

To create an org-manager user, we need to create two RoleBindings in the ORG namespace, where ORG is the organisation associated with the org-manager:
* one granting all the org-manager permissions on the CF custom resources
* one granting the SubNamespaceAnchor management permissions, with the `propagate.hnc.x-k8s.io/none: "true"` annotation.

All other users are created as RoleBindings at the appropriate level:
* global roles (admin, admin-read-only, global-auditor) are created in `cf`
    * they are automatically propagated to child org and space sub-namespaces, both those that exist at the time of creation and those subsequently created
* org level roles are created in their ORG namespace
    * they are automatically propagated to space sub-namespaces
* space level roles are created in their SPACE namespace, and apply only there.

**Comment by mnitchev** [comment]
We've updated the [Org support proposal](https://docs.google.com/document/d/1Pftj2RFayUPV4xc58efLI-0_m4wLLJWy7YhdJwRfu1Q/edit#heading=h.drik4ws976b7) with the results of this explore. This explore however does not cover the multicluster support that the proposal doc has. We think that it could be done with [kubefed](https://github.com/kubernetes-sigs/kubefed), although this would be difficult to do. We are also not sure how balancing resources across clusters would work, as there is no "out of the box" solution.
